name: satdepth
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h497a2fe_1
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.1=hd32f23e_0
  - boost-cpp=1.74.0=h359cf19_5
  - bottleneck=1.3.5=py38h7deecbd_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2023.5.7=py38h06a4308_0
  - cffi=1.15.0=py38h3931269_0
  - cfitsio=4.0.0=h9a35b8e_0
  - cudatoolkit=10.2.89=h8f6ccaa_9
  - curl=7.83.1=h2283fc2_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py38h709712a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.8=h27087fc_0
  - flit-core=3.6.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - gdal=3.4.0=py38he48826a_8
  - geos=3.10.1=h9c3ff4c_1
  - geotiff=1.7.0=h90a4e78_5
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h4df4325_104
  - icu=69.1=h9c3ff4c_0
  - importlib-metadata=4.10.1=py38h578d9bd_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=6.7.0=py38he5a9106_0
  - ipython=7.31.0=py38h578d9bd_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py38h578d9bd_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.1.1=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38h578d9bd_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kealib=1.4.14=h87e4c3c_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.3.2=py38h1fd1430_1
  - krb5=1.19.3=h08a2579_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libcurl=7.83.1=h2283fc2_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h9c3ff4c_4
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgdal=3.4.0=h1504ab5_8
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.70.2=h174f98d_4
  - libiconv=1.17=h166bdaf_0
  - libkml=1.3.0=h238a007_1014
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.47.0=he49606f_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libpq=14.2=h676c864_0
  - librttopo=1.1.0=h30b5eef_8
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialite=5.0.1=hf3ee066_12
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.12=h885dcf4_1
  - libzip=1.8.0=h1c5bbd1_1
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py38h497a2fe_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h5c7f4ab_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1005
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py38h1e0a361_2
  - mkl_fft=1.3.0=py38h5c078b8_1
  - mkl_random=1.2.0=py38hc5bc63f_1
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.0=py38h578d9bd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - ninja=1.10.2=h4bd325d_1
  - notebook=6.4.7=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.72=hb5efdd6_0
  - numexpr=2.7.3=py38hb2eb853_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.8=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.17.0.1=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py38h8e6f84c_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=21.11.0=ha39eefc_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.2=hce44dc1_0
  - proj=8.2.0=h277dcde_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.24=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38h497a2fe_0
  - python=3.8.12=hf930737_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyzmq=22.3.0=py38h2035c66_1
  - readline=8.1=h46c0cb4_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.4.0=py38h578d9bd_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.36.0=h9cd32fc_2
  - terminado=0.12.1=py38h578d9bd_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - tiledb=2.5.3=hf3d3071_0
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py38h497a2fe_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - tzcode=2022a=h166bdaf_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - xerces-c=3.2.3=h8ce2273_4
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.1=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - accelerate==1.0.1
    - affine==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==0.5.1
    - anyio==3.5.0
    - argparse==1.4.0
    - astroid==2.9.3
    - async-timeout==4.0.2
    - autopep8==1.6.0
    - babel==2.9.1
    - braceexpand==0.1.7
    - cachetools==4.2.4
    - charset-normalizer==2.0.10
    - click==8.0.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cmake==3.26.4
    - config==0.5.1
    - configargparse==1.5.3
    - cython==0.29.35
    - deprecated==1.2.13
    - einops==0.3.0
    - filelock==3.4.2
    - frozenlist==1.3.0
    - fsspec==2024.9.0
    - future==0.18.2
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - h5py==3.1.0
    - huggingface-hub==0.25.2
    - idna==3.3
    - imageio==2.13.5
    - imgaug==0.4.0
    - isort==5.10.1
    - joblib==1.1.0
    - json5==0.9.6
    - jupyter-server==1.13.3
    - jupyterlab==3.2.8
    - jupyterlab-server==2.10.3
    - kornia==0.4.1
    - lazy-object-proxy==1.7.1
    - lit==16.0.6
    - loguru==0.5.3
    - markdown==3.3.6
    - mccabe==0.6.1
    - mpmath==1.3.0
    - msgpack==1.0.3
    - multidict==5.2.0
    - nbclassic==0.3.5
    - networkx==2.6.3
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.1.1
    - opencv-python==4.4.0.46
    - pandas==2.0.2
    - peft==0.13.2
    - platformdirs==2.4.1
    - protobuf==3.20.0
    - psutil==7.0.0
    - ptflops==0.7.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pydeprecate==0.3.0
    - pylint==2.12.2
    - pytorch-lightning==1.3.5
    - pytz==2021.3
    - pywavelets==1.2.0
    - pyyaml==5.4.1
    - rasterio==1.3.11
    - ray==1.9.2
    - redis==4.1.1
    - regex==2024.11.6
    - requests==2.27.1
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - safetensors==0.4.5
    - scikit-image==0.19.1
    - scipy==1.7.3
    - shapely==1.8.0
    - sniffio==1.2.0
    - snuggs==1.4.7
    - sympy==1.12
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tifffile==2021.11.2
    - timm==1.0.9
    - tokenizers==0.20.3
    - toml==0.10.2
    - torch==2.0.1
    - torchmetrics==0.7.0
    - torchprofile==0.0.4
    - torchvision==0.15.2
    - tqdm==4.62.3
    - transformers==4.46.3
    - triton==2.0.0
    - tzdata==2023.3
    - urllib3==1.26.8
    - utm==0.7.0
    - webdataset==0.2.100
    - websocket-client==1.2.3
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - yacs==0.1.8
    - yarl==1.7.2
